### ISSUE TITLE
Configuration parser does interpolation on username and password

### ISSUE THREAD

**Issue by commonquail** [coddingtonbear/jirafs#42]
This makes it impossible to use a username or password containing a `%`. There are two errors included at the end, the first from attempting to save a password and the second from pulling after manually configuring the password.

By escaping the  `%` with another `%`, jirafs proceeds to authentication but instead submits a now invalid password.

[There is something called `RawConfigParser`](https://stackoverflow.com/a/2538141) that avoids interpolation, which is probably really what is wanted here, but I can't tell if that's from the same package jirafs uses.

```
JIRA Password (https://jira.dsg.dk): 
Save JIRA Password (Y/N)? y
Traceback (most recent call last):
  File "/usr/local/bin/jirafs", line 9, in <module>
    load_entry_point('jirafs==1.16', 'console_scripts', 'jirafs')()
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/cmdline.py", line 102, in main
    extra, jira=jira, path=args.folder, command_name=command_name
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/plugin.py", line 266, in execute_command
    cmd.handle(**kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/plugin.py", line 303, in handle
    return self.cmd(*args, **kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/plugin.py", line 307, in cmd
    self.main(*args, **kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/commands/pull.py", line 13, in main
    fetch_result = run_command_method_with_kwargs('fetch', folder=folder)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/utils.py", line 90, in run_command_method_with_kwargs
    return getattr(installed_commands[command](), method)(**kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/commands/fetch.py", line 75, in main
    for filename in folder.get_remotely_changed():
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/ticketfolder.py", line 684, in get_remotely_changed
    getattr(self.issue.fields, 'attachment', []),
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/ticketfolder.py", line 236, in issue
    self._issue = self.jira.issue(self.ticket_number)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/ticketfolder.py", line 229, in jira
    config=self.get_config()
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/utils.py", line 253, in <lambda>
    return lambda domain, config=None: get_jira(domain, config)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/utils.py", line 211, in get_jira
    config.set(section, 'password', value)
  File "/usr/lib/python3.4/configparser.py", line 1167, in set
    super().set(section, option, value)
  File "/usr/lib/python3.4/configparser.py", line 872, in set
    value)
  File "/usr/lib/python3.4/configparser.py", line 382, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'some%password' at position 18
```
```
$ jirafs pull
Traceback (most recent call last):
  File "/usr/local/bin/jirafs", line 9, in <module>
    load_entry_point('jirafs==1.16', 'console_scripts', 'jirafs')()
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/cmdline.py", line 102, in main
    extra, jira=jira, path=args.folder, command_name=command_name
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/plugin.py", line 266, in execute_command
    cmd.handle(**kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/plugin.py", line 303, in handle
    return self.cmd(*args, **kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/plugin.py", line 307, in cmd
    self.main(*args, **kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/commands/pull.py", line 13, in main
    fetch_result = run_command_method_with_kwargs('fetch', folder=folder)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/utils.py", line 90, in run_command_method_with_kwargs
    return getattr(installed_commands[command](), method)(**kwargs)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/commands/fetch.py", line 75, in main
    for filename in folder.get_remotely_changed():
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/ticketfolder.py", line 684, in get_remotely_changed
    getattr(self.issue.fields, 'attachment', []),
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/ticketfolder.py", line 236, in issue
    self._issue = self.jira.issue(self.ticket_number)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/ticketfolder.py", line 229, in jira
    config=self.get_config()
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/utils.py", line 253, in <lambda>
    return lambda domain, config=None: get_jira(domain, config)
  File "/home/quail/.local/lib/python3.4/site-packages/jirafs/utils.py", line 213, in get_jira
    login_data['password'] = config.get(section, 'password')
  File "/usr/lib/python3.4/configparser.py", line 773, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 374, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 423, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%p'"
```

**Comment by coddingtonbear** [comment]
Ooo -- good call; jirafs does use the built-in `configparser` module, so your suggestion of using `RawConfigParser` instead is a good one.  Could you post a pull request for this?
